### ISSUE TITLE
`MapEntry`

### ISSUE THREAD

**Issue by dmfs** [dmfs/optional#18]
I've just been in need of an adapter to retrieve an element from a `Map` in a null-safe manner.

Something like this

```
Map<String, List<String>> map = …;
…
Optional<String> strings = new MapEntry<>(map, "key");
```
`MapEntry` would be absent if `"key"` is not in the map.

Question: how would we handle `null` values in the map? Would the optional be absent or the value of the `Optional` be `null`?  
My idea would be to treat `null` values like absent values.

**Comment by lemonboston** [comment]
It sounds better for me, too, to have absent for `null` values. I guess it would probably be clearer if they are not allowed in `Map`s in the first place but we can't change that.
