### ISSUE TITLE
`AbstractDelegatedOptional`

### ISSUE THREAD

**Issue by dmfs** [dmfs/optional#21]
In order to compose `Optional`s more easily, as a developer I want an `AbstractDelegatedOptional` which delegates each call to the optional passed to the ctor. All methods (including `hashCode`, `equals` and `toString`) are final and delegate execution to the object passed to the ctor.

The class is meant to serve as the super class of other Optionals which are then composed like this

```java
public final class EasyOptional extends AbstractDelegatedOptional<MyType>
{
    public EasyOptional(ParamType param)
    {
        super(new Mapped(someFunction, new SomeOptionalAdapter(param)));
    }
}
```

Although we generally despise inheritance, this is probably the lesser of two evils (the other one being writing the same boiler plate code over and over again). Also, since all methods are final you can't mess it up.

**Comment by dmfs** [comment]
This post covers the same issue: http://www.yegor256.com/2017/01/31/decorating-envelopes.html

**Comment by dmfs** [comment]
Not sure about the name though. Should it be `AbstractDelegatingOptional`? Or anything else?

**Comment by lemonboston** [comment]
`AbstractDelegatingOptional` sounds correct for me, even thought it's not very 'nice'.
Totally agree with this 'pattern' to create a base delegating class.
(Side note: I suppose this is what is automatic in Kotlin.)

**Comment by dmfs** [comment]
We could omit the "Abstract" part and just call it `DelegatingOptional`.

Right, in Kotlin this wouldn't be necessary at all.

**Comment by dmfs** [comment]
This how `FirstPresent` would look like in Kotlin:

```kotlin
class FirstPresent<T> private constructor(delegate: Optional<T>) : Optional<T> by delegate {
    constructor(i: Iterable<Optional<T>>) : this(First(PresentValues(i)));
}
```

That's it. Just one constructor.

This is how it would look like with a `DelegatingOptional` in Java:
```java
public final class FirstPresent<T> extends DelegatingOptional<T>
{

    public FirstPresent(Iterable<Optional<T>> iterable)
    {
        super(new First<>(new PresentValues<>(iterable)));
    }
}
```

Also quite short but requires an abstract class.

**Comment by dmfs** [comment]
How about just `Delegating`? Since it's essentially a decorator we should not add the type name to the class name,
