### ISSUE TITLE
Delete Obligatory decorator

### ISSUE THREAD

**Issue by dmfs** [dmfs/optional#4]
@lemonboston
As discussed on Slack an "Obligatory" is not really an `Optional` anymore. So should we remove it?

**Comment by lemonboston** [comment]
Yes, I think we should.
I think if we want to create a lazily evaluated value from an `Optional` and a fallback value, I think it could be done as a `Lazy`.
I am going to submit the PR to remove the class.

**Comment by dmfs** [comment]
Done.
